Test IfcConvert only on single file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -121,20 +121,23 @@ jobs:
           sudo make -j $(nproc)
           sudo make install
 
-      - name: Run IfcConvert on Sample files
-        run: |
-          (find test/input src/bonsai/test/files -name '*.ifc' | while read i; do \
-            echo $i | tee -a log; \
-            timeout 1m "$(which IfcConvert)" -yv "$i" "$i.obj" --validate >> log 2>&1; \
-            echo $i $? >> statuses; \
-          done) || true
-          echo Failed 
-          grep -v 0$ statuses
-          grep -v 0$ statuses | wc -l
-          echo Succeeded
-          grep 0$ statuses
-          grep 0$ statuses | wc -l
+      # - name: Run IfcConvert on Sample files
+      #   run: |
+      #     (find test/input src/bonsai/test/files -name '*.ifc' | while read i; do \
+      #       echo $i | tee -a log; \
+      #       timeout 1m "$(which IfcConvert)" -yv "$i" "$i.obj" --validate >> log 2>&1; \
+      #       echo $i $? >> statuses; \
+      #     done) || true
+      #     echo Failed
+      #     grep -v 0$ statuses
+      #     grep -v 0$ statuses | wc -l
+      #     echo Succeeded
+      #     grep 0$ statuses
+      #     grep 0$ statuses | wc -l
 
+      - name: Run IfcConvert on Sample file
+        run: |
+          IfcConvert test/input/acad2010_walls.ifc test/input/acad2010_walls.obj
 
       - name: Test ifcopenshell-python
         run: |
